"""Tests for BrainForge data models."""

from uuid import UUID

import pytest

from src.models.agent_run import AgentRun, AgentRunCreate, AgentRunStatus
from src.models.embedding import Embedding, EmbeddingCreate
from src.models.link import Link, LinkCreate, RelationType
from src.models.note import Note, NoteCreate, NoteType
from src.models.version_history import VersionHistory, VersionHistoryCreate


class TestNoteModel:
    """Test Note model functionality."""

    def test_note_creation(self):
        """Test creating a basic note."""
        note_data = NoteCreate(
            content="Test note content",
            note_type=NoteType.FLEETING,
            created_by="test@example.com"
        )

        note = Note(
            id=UUID('12345678-1234-5678-1234-567812345678'),
            content=note_data.content,
            note_type=note_data.note_type,
            created_by=note_data.created_by,
            version=1
        )

        assert note.content == "Test note content"
        assert note.note_type == NoteType.FLEETING
        assert note.created_by == "test@example.com"
        assert note.version == 1

    def test_note_ai_generated_validation(self):
        """Test AI-generated note validation."""
        # This should fail without justification
        with pytest.raises(ValueError):
            NoteCreate(
                content="AI-generated content",
                note_type=NoteType.AGENT_GENERATED,
                created_by="ai@example.com",
                is_ai_generated=True,
                ai_justification=None  # Missing justification
            )

        # This should succeed with justification
        note_data = NoteCreate(
            content="AI-generated content",
            note_type=NoteType.AGENT_GENERATED,
            created_by="ai@example.com",
            is_ai_generated=True,
            ai_justification="Generated by research agent v1.0"
        )

        assert note_data.is_ai_generated is True
        assert note_data.ai_justification is not None


class TestLinkModel:
    """Test Link model functionality."""

    def test_link_creation(self):
        """Test creating a link between notes."""
        link_data = LinkCreate(
            source_note_id=UUID('11111111-1111-1111-1111-111111111111'),
            target_note_id=UUID('22222222-2222-2222-2222-222222222222'),
            relation_type=RelationType.RELATED,
            created_by="user@example.com"
        )

        link = Link(
            id=UUID('33333333-3333-3333-3333-333333333333'),
            source_note_id=link_data.source_note_id,
            target_note_id=link_data.target_note_id,
            relation_type=link_data.relation_type,
            created_by=link_data.created_by
        )

        assert link.relation_type == RelationType.RELATED
        assert link.source_note_id != link.target_note_id


class TestEmbeddingModel:
    """Test Embedding model functionality."""

    def test_embedding_creation(self):
        """Test creating an embedding."""
        embedding_data = EmbeddingCreate(
            note_id=UUID('44444444-4444-4444-4444-444444444444'),
            vector=[0.1, 0.2, 0.3],
            model_version="text-embedding-3-small"
        )

        embedding = Embedding(
            id=UUID('55555555-5555-5555-5555-555555555555'),
            note_id=embedding_data.note_id,
            vector=embedding_data.vector,
            model_version=embedding_data.model_version
        )

        assert len(embedding.vector) == 3
        assert embedding.model_version == "text-embedding-3-small"


class TestVersionHistoryModel:
    """Test VersionHistory model functionality."""

    def test_version_history_creation(self):
        """Test creating version history."""
        version_data = VersionHistoryCreate(
            note_id=UUID('66666666-6666-6666-6666-666666666666'),
            version=2,
            content="Updated note content",
            created_by="user@example.com"
        )

        version = VersionHistory(
            id=UUID('77777777-7777-7777-7777-777777777777'),
            note_id=version_data.note_id,
            version=version_data.version,
            content=version_data.content,
            created_by=version_data.created_by
        )

        assert version.version == 2
        assert version.content == "Updated note content"


class TestAgentRunModel:
    """Test AgentRun model functionality."""

    def test_agent_run_creation(self):
        """Test creating an agent run."""
        agent_run_data = AgentRunCreate(
            agent_name="research_agent",
            agent_version="1.0.0",
            input_parameters={"topic": "AI knowledge management"},
            status=AgentRunStatus.PENDING_REVIEW
        )

        agent_run = AgentRun(
            id=UUID('88888888-8888-8888-8888-888888888888'),
            agent_name=agent_run_data.agent_name,
            agent_version=agent_run_data.agent_version,
            input_parameters=agent_run_data.input_parameters,
            status=agent_run_data.status
        )

        assert agent_run.agent_name == "research_agent"
        assert agent_run.agent_version == "1.0.0"
        assert agent_run.status == AgentRunStatus.PENDING_REVIEW
